### ISSUE TITLE
why error? 

### ISSUE THREAD

**Issue by hotsmile** [dirk-weimar/confluence-chatbot#1]
when i execute the step 
docker run -it --rm -v $(pwd):/app -e ACTION=collect-data confluence-chatbot
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
python: can't open file '/app/app.py': [Errno 13] Permission denied
the current directory ,i hava granted it 777 yet

**Comment by dirk-weimar** [comment]
I have no experience with podman. Maybe [try this version](https://github.com/dirk-weimar/let-me-confluence-that-for-you) instead. It does pretty much the same but has a graphical user interface and works without docker.
